"""initial migration

Revision ID: da2aa2293c75
Revises: 
Create Date: 2026-05-18 09:16:22.598066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2aa2293c75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ds_task_code', sa.BigInteger(), nullable=True),
    sa.Column('folder_id', sa.BigInteger(), nullable=True, comment='所属文件夹 id'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同文件夹内排序'),
    sa.Column('previous_status', sa.String(length=50), nullable=True, comment='暂停前的状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_folder',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父文件夹 id, NULL 为根'),
    sa.Column('depth', sa.Integer(), nullable=True, comment='层级: 0=一级, 1=二级, 2=三级'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同层级排序'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('last_check_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='项目名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='项目编码 — 用于 DS 工作流命名前缀'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('color', sa.String(length=16), nullable=True, comment='项目主题色 — 系统按 id 分配 8 色调色板'),
    sa.Column('status', sa.Integer(), nullable=True, comment='1=启用 0=禁用'),
    sa.Column('is_default', sa.Integer(), nullable=True, comment='1=系统默认未分组项目，不可删'),
    sa.Column('owner_id', sa.BigInteger(), nullable=True, comment='负责人 user_id'),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True, comment='所属项目 — NULL 时归属默认未分组项目'),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('source_table', sa.String(length=128), nullable=False),
    sa.Column('target_table', sa.String(length=128), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=True),
    sa.Column('increment_column', sa.String(length=128), nullable=True),
    sa.Column('field_mapping', sa.Text(), nullable=True, comment='字段映射 JSON 数组 [{kind,src,dst,type},...]'),
    sa.Column('where_clause', sa.Text(), nullable=True, comment='源端 WHERE 过滤条件，支持 ${bizdate} 等变量'),
    sa.Column('split_pk', sa.String(length=128), nullable=True, comment='DataX splitPk 切分键，提升并发'),
    sa.Column('write_mode', sa.String(length=32), nullable=True, comment='insert / replace / update'),
    sa.Column('channel', sa.Integer(), nullable=True, comment='DataX 并发通道数，1-32'),
    sa.Column('pre_sql', sa.Text(), nullable=True, comment='导入前 SQL 列表 JSON 数组（目标库执行）'),
    sa.Column('post_sql', sa.Text(), nullable=True, comment='导入后 SQL 列表 JSON 数组（目标库执行）'),
    sa.Column('ds_workflow_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sys_notify_channel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_oauth_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=True),
    sa.Column('app_secret', sa.String(length=255), nullable=True),
    sa.Column('redirect_uri', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_resource_access',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('dept_id', sa.BigInteger(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_openid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('word_root',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('en', sa.String(length=64), nullable=False, comment='英文词根'),
    sa.Column('cn', sa.String(length=64), nullable=False, comment='中文名'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='business/technical/metric'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='说明'),
    sa.Column('example', sa.String(length=255), nullable=True, comment='示例用法'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en')
    )
    op.create_table('workflow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('dag_json', sa.JSON(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('schedule_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_run_status', sa.String(length=50), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('last_run_duration', sa.Integer(), nullable=True),
    sa.Column('ds_process_code', sa.BigInteger(), nullable=True),
    sa.Column('ds_schedule_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_role_permission')
    op.drop_table('workflow')
    op.drop_table('word_root')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_resource_access')
    op.drop_table('sys_permission')
    op.drop_table('sys_oauth_config')
    op.drop_table('sys_notify_channel')
    op.drop_table('sys_config')
    op.drop_table('sync_task')
    op.drop_table('project')
    op.drop_table('data_source')
    op.drop_table('component_folder')
    op.drop_table('component')
    # ### end Alembic commands ###
